---
- name: restart LLDP
  service:
    name: lldpd
    state: restarted

- name: restart NTPD
  service:
    name: ntp
    state: restarted

- name: reload netqagent
  command: "netq config restart agent"
