---
- name: Add NetQ 4.x Repository
  apt_repository:
    repo: deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-4 netq-4.0
    state: present

- name: Copy authentication key file
  ansible.builtin.copy:
    src: /etc/netq/.loginkeys.aes
    dest: /etc/netq/
    owner: root
    group: root
    mode: "0666"
  become: yes

- name: Stop NTP
  systemd:
    name: ntp
    state: stopped

- name: Disable NTP
  systemd:
    name: ntp
    enabled: no

- name: Start NTP in a VRF
  systemd:
    name: ntp@mgmt
    state: started
    daemon_reload: yes

- name: Enable NTP in a VRF on boot
  systemd:
    name: ntp@mgmt
    enabled: yes

- name: Stop rsyslog
  systemd:
    name: rsyslog
    state: stopped
  ignore_errors: yes

- name: Disable rsyslog
  systemd:
    name: rsyslog
    enabled: no

- name: Copy rsyslog configuration file
  template:
    src: 11-remotesyslog.j2
    dest: /etc/rsyslog.d/11-remotesyslog.conf
    backup: yes

- name: Start rsyslog in a VRF
  systemd:
    name: rsyslog
    state: started
    daemon_reload: yes
  ignore_errors: yes

- name: Enable rsyslog in a VRF on boot
  systemd:
    name: rsyslog
    enabled: yes

- name: Install NetQ Agent on CL
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - netq-agent

- name: Start NetQ
  systemd:
    name: netqd
    state: started
    daemon_reload: yes

- name: Enable NetQ Agent
  systemd:
    name: netqd
    enabled: yes

- name: Configure NetQ Agent
  command: netq config add agent server "{{ netqts }}" vrf mgmt
  become: yes

- name: Configure NetQ CLI
  command: netq config add cli server "{{ netqts }}" vrf mgmt
  become: yes

- name: Fix
  ansible.builtin.shell:
  cmd: sed -i 's/air.cumulusnetworks.com/air.nvidia.com/' /etc/cumulus-air/agent.ini

- name: Restart NetQ Agent
  systemd:
    name: netq-agent
    state: restarted

- name: Restart AIR agent (configures NetQ Agent)
  systemd:
    name: air-agent@mgmt.service
    state: restarted

- name: Restart NetQ CLI
  command: netq config restart cli
  become: yes
