---

- name: Add NetQ 3.x Repository
  apt_repository:
    repo: deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-3.0
    state: present

- name: Stop NTP
  systemd:
    name: ntp
    state: stopped

- name: Disable NTP
  systemd:
    name: ntp
    enabled: no

- name: Start NTP in a VRF
  systemd:
    name: ntp@mgmt
    state: started
    daemon_reload: yes

- name: Enable NTP in a VRF on boot
  systemd:
    name: ntp@mgmt
    enabled: yes

- name: Stop rsyslog
  systemd:
    name: rsyslog
    state: stopped
  ignore_errors: yes

- name: Disable rsyslog
  systemd:
    name: rsyslog
    enabled: no

- name: Copy rsyslog configuration file
  template:
    src: 11-remotesyslog.j2
    dest: /etc/rsyslog.d/11-remotesyslog.conf
    backup: yes

- name: Start rsyslog in a VRF
  systemd:
    name: rsyslog
    state: started
    daemon_reload: yes

- name: Enable rsyslog in a VRF on boot
  systemd:
     name: rsyslog
     enabled: yes

- name: Install NetQ Agent and NetQ CLI
  apt:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - netq-agent
    - netq-apps

- name: Start NetQ
  systemd:
    name: netqd
    state: started
    daemon_reload: yes

- name: Enable NetQ Agent
  systemd:
     name: netqd
     enabled: yes

- name: Configure NetQ Agent
  command: netq config add agent server "{{ netqts }}" vrf mgmt
  become: yes

- name: Configure NetQ CLI
  command: netq config add cli server "{{ netqts }}" vrf mgmt
  become: yes

- name: Restart NetQ Agent and NetQ CLI
  systemd:
    name: netq-agent
    state: restarted

- name: Restart AIR agent (configures NetQ Agent)
  systemd:
    name: air-agent
    state: restarted
